### ISSUE TITLE
Local Installation Guide

### ISSUE THREAD

**Issue by annie-bhaiya** [riteshk-007/nextjs-store#1]
Can you please provide a guide for the local installation of the project. Particularly about how to setup mongodb part and what all to enable in firebase

**Comment by riteshk-007** [comment]
Namaste, thank you for your interest in my project. I have created a README.md file in my GitHub repository, where you can find the guide for the local installation of the project. You can also find the instructions for setting up MongoDB and Firebase in the Installation section of the README.md file. Please follow the steps carefully and let me know if you face any issues. I hope you enjoy using my project. 😊

**Comment by annie-bhaiya** [comment]
Thanks

**Comment by annie-bhaiya** [comment]
Thanks
